name: "attic-action"
author: "Ryan Cao"
description: "Cache Nix derivations with attic"

branding:
  icon: "layers"
  color: "blue"

inputs:
  endpoint:
    description: "Attic endpoint"
    required: true
  cache:
    description: "Attic cache name"
    required: true
  skip-push:
    description: "Disable pushing to the cache automatically"
    required: false
  token:
    description: "Attic authorization token"
    required: false
  skip-use:
    description: "Set to true to skip using attic cache as a substituter"
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
  post: "dist/index.js"
